export const dataVocabulary = [
    
        {
            id: 1,
            word: "Annual",
            synonyms: "Yearly, once a year, every year",
            antonyms: "",
            meanings: "Hàng năm, mỗi năm 1 lần",
        },
        {
            id: 2,
            word: "Get on",
            synonyms: "Board",
            antonyms: "Get off",
            meanings: "Lên#xuống(tàu, xe, máy bay,...)",
        },
        {
            id: 3,
            word: "Ride a/the bus",
            synonyms: "Take a/the bus",
            antonyms: "",
            meanings: "Đi bằng xe buýt",
        },
        {
            id: 4,
            word: "Give +S.O a lift/ a ride",
            synonyms: "",
            antonyms: "Get + S.O a lift/ a ride",
            meanings: "Cho quá giang # đi quá giang",
        },
        {
            id: 5,
            word: "Relocate",
            synonyms: "Move to, Transfer(v): chuyến đi, chuyến công tác",
            antonyms: "",
            meanings: "Chuyển đến, dời đến",
        },
        {
            id: 6,
            word: "Merger",
            synonyms: "Combination",
            antonyms: "",
            meanings: "Sự xác nhập",
        },
        {
            id: 7,
            word: "Complimentary",
            synonyms: "Free",
            antonyms: "",
            meanings: "Miễn phí, cho tặng",
        },
        {
            id: 8,
            word: "Itinerary",
            synonyms: "Travel details, detailed schedule",
            antonyms: "",
            meanings: "Lịch chi tiết của một chuyến đi",
        },
        {
            id: 9,
            word: "Previous",
            synonyms: "Ago, last",
            antonyms: "Upcoming",
            meanings: "Trước đó # sắp diễn ra",
        },
        {
            id: 10,
            word: "Recruit",
            synonyms: "Hire, employ, seek, look for, search for",
            antonyms: "",
            meanings: "Tuyển dụng",
        },
        {
            id: 11,
            word: "Wait in line",
            synonyms: "Stand in line, line up",
            antonyms: "",
            meanings: "Xếp hàng",
        },
        {
            id: 12,
            word: "Current",
            synonyms: "Present",
            antonyms: "",
            meanings: "Hiện tại",
        },
        {
            id: 13,
            word: "Elevator",
            synonyms: "Lift",
            antonyms: "",
            meanings: "Thang máy",
        },
        {
            id: 14,
            word: "Escalator",
            synonyms: "",
            antonyms: "",
            meanings: "Thang cuốn",
        },
        {
            id: 15,
            word: "Out of service",
            synonyms: "Out of order",
            antonyms: "",
            meanings: "Ngưng phục vụ, hết, hư",
        },
        {
            id: 16,
            word: "Due to",
            synonyms: "Because of, owing to",
            antonyms: "",
            meanings: "Bởi vì",
        },
        {
            id: 17,
            word: "Display",
            synonyms: "Layout, exhibit",
            antonyms: "",
            meanings: "Trưng bày",
        },
        {
            id: 18,
            word: "Occupation",
            synonyms: "Profession, job, career",
            antonyms: "",
            meanings: "Nghề nghiệp",
        },
        {
            id: 19,
            word: "Decoration",
            synonyms: "Ornamentation",
            antonyms: "",
            meanings: "Sự trang trí",
        },
        {
            id: 20,
            word: "As of + ngày tháng",
            synonyms: "",
            antonyms: "",
            meanings: "Kể từ...trở đi",
        },
        {
            id: 21,
            word: "From now on",
            synonyms: "",
            antonyms: "",
            meanings: "Từ giờ trở đi",
        },
        {
            id: 22,
            word: "Refund",
            synonyms: "Money back (dùng khi mua hàng hóa)",
            antonyms: "",
            meanings: "Từ liên quan: policy, receipt, purchase,...",
        },
        {
            id: 23,
            word: "Reimburse(v) Reimbursement",
            synonyms: "Money back (dùng khi đi công tác)",
            antonyms: "",
            meanings: "Tiền thanh lại sau khi đi công tác. Từ liên quan: expense (chi phí), receipt, submit(nộp)...",
        },
        {
            id: 24,
            word: "Reduce",
            synonyms: "Cut, decrease, lessen",
            antonyms: "Rise, increase grow",
            meanings: "Giảm # Tăng. Từ liên quan: cost, price, budget, finanacial,...",
        },
        {
            id: 25,
            word: "Be in charge of",
            synonyms: "Take care of, take over",
            antonyms: "",
            meanings: "Đảm nhận",
        },
        {
            id: 26,
            word: "Postpone",
            synonyms: "Delay, put off, push back",
            antonyms: "",
            meanings: "Hoãn",
        },
        {
            id: 27,
            word: "Emergency",
            synonyms: "Urgent",
            antonyms: "",
            meanings: "Khẩn cấp",
        },
        {
            id: 28,
            word: "In advance",
            synonyms: "Before, prior to",
            antonyms: "",
            meanings: "Trước",
        },
        {
            id: 29,
            word: "Mandatory",
            synonyms: "Compulsory, must",
            antonyms: "Chú ý: Khi đề cho Requirement(s) thì tìm Require hoặc 1 trong 3 từ này",
            meanings: "Phải, bắt buộc",
        },
        {
            id: 30,
            word: "Inform",
            synonyms: "Announce, notify(v)",
            antonyms: "",
            meanings: "Thông báo",
        },
        {
            id: 31,
            word: "Get together",
            synonyms: "Meet together, gather",
            antonyms: "",
            meanings: "Gặp nhau",
        },
        {
            id: 32,
            word: "Focus on",
            synonyms: "Concentrate on",
            antonyms: "",
            meanings: "Tập trung vào",
        },
        {
            id: 33,
            word: "Cut",
            synonyms: "Trim, mow",
            antonyms: "",
            meanings: "Cắt, chặt, Cắt cỏ",
        },
        {
            id: 34,
            word: "Grass",
            synonyms: "Lawn",
            antonyms: "",
            meanings: "Cỏ",
        },
        {
            id: 35,
            word: "Income",
            synonyms: "Revenue, profit(n)",
            antonyms: "",
            meanings: "Lợi nhuận, thu nhập",
        },
        {
            id: 36,
            word: "Be out",
            synonyms: "Step out, go outside",
            antonyms: "",
            meanings: "Đi ra ngoài",
        },
        {
            id: 37,
            word: "Reduce rate",
            synonyms: "Discount, sale off, bargain, rebate",
            antonyms: "",
            meanings: "Giảm giá",
        },
        {
            id: 38,
            word: "50% discount",
            synonyms: "Half off, buy 1 get 1 free",
            antonyms: "",
            meanings: "Giảm 50%",
        },
        {
            id: 39,
            word: "Adjust",
            synonyms: "Test, check",
            antonyms: "",
            meanings: "Kiểm tra, điều chỉnh",
        },
        {
            id: 40,
            word: "Elect",
            synonyms: "Vote(v)",
            antonyms: "",
            meanings: "Bầu cử, bình chọn",
        }
    
]